# 定义 SPEC2006 测试命令
declare -A spec_commands
spec_commands[astar]="-c ./astar_base.x86_64_sse --option=\"rivers.cfg \""
spec_commands[bzip2]="-c ./bzip2_base.x86_64_sse --option=\"input/input.source 280\""
spec_commands[cactusADM]="-c ./cactusADM_base.x86_64_sse --option=\"benchADM.par \""
spec_commands[calculix]="-c ./calculix_base.x86_64_sse --option=\"hyperviscoplastic \""
spec_commands[dealII]="-c ./dealII_base.x86_64_sse --option=\"23 \""
spec_commands[gamess]="-c ./gamess_base.x86_64_sse -i input/triazolium.config"
spec_commands[gcc]="-c ./gcc_base.x86_64_sse --option=\"input/scilab.i -o scilab.s\""
spec_commands[GemsFDTD]="-c ./GemsFDTD_base.x86_64_sse"
spec_commands[gobmk]="-c ./gobmk_base.x86_64_sse -i input/score2.tst --option=\"--quiet --mode gtp \""
spec_commands[gromacs]="-c ./gromacs_base.x86_64_sse --option=\"-silent -deffnm input/gromacs -nice 0\""
spec_commands[h264ref]="-c ./h264ref_base.x86_64_sse --option=\"-d input/sss_encoder_main.cfg\""
spec_commands[hmmer]="-c ./hmmer_base.x86_64_sse --option=\"input/nph3.hmm input/swiss41 \""
spec_commands[lbm]="-c ./lbm_base.x86_64_sse --option=\"3000 reference.dat 0 0 100_100_130_ldc.of \""
spec_commands[leslie3d]="-c ./leslie3d_base.x86_64_sse -i leslie3d.in"
spec_commands[libquantum]="-c ./libquantum_base.x86_64_sse --option=\"1397 8 \""
spec_commands[mcf]="-c ./mcf_base.x86_64_sse --option=\"inp.in \""
spec_commands[milc]="-c ./milc_base.x86_64_sse -i input/su3imp.in"
spec_commands[namd]="-c ./namd_base.x86_64_sse --option=\"--input input/namd.input --iterations 38 --output namd.out\""
spec_commands[omnetpp]="-c ./omnetpp_base.x86_64_sse --option=\"omnetpp.ini \""
spec_commands[perlbench]="-c ./perlbench_base.x86_64_sse --option=\"-Ilib checkspam.pl 2500 5 25 11 150 1 1 1 1 \""
spec_commands[povray]="-c ./povray_base.x86_64_sse --option=\"SPEC-benchmark-ref.ini \""
spec_commands[sjeng]="-c ./sjeng_base.x86_64_sse --option=\"input/ref.txt\""
spec_commands[soplex]="-c ./soplex_base.x86_64_sse --option=\"-s1 -e -m45000 pds-50.mps  \""
spec_commands[sphinx_livepretend]="-c ./sphinx_livepretend_base.x86_64_sse --option=\"ctlfile . input/args.an4\""
spec_commands[tonto]="-c ./tonto_base.x86_64_sse"
spec_commands[wrf]="-c ./wrf_base.x86_64_sse"
spec_commands[xalancbmk]="-c ./xalancbmk_base.x86_64_sse --option=\"-v t5.xml xalanc.xsl \""
spec_commands[zeusmp]="-c ./zeusmp_base.x86_64_sse"
